[workspace]
authors = ["ThePieroCV <piero.casusolv@pucp.edu.pe>"]
channels = ["conda-forge"]
name = "i40"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
torch = { version = ">=2.7.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.22.1", index = "https://download.pytorch.org/whl/cu128" }
roboflow = ">=1.1.66, <2"
opencv-python = ">=4.11.0.86, <5"
ultralytics = ">=8.3.158, <9"
jupyterlab = ">=4.4.3, <5"
