[workspace]
authors = ["ThePieroCV <piero.casusolv@pucp.edu.pe>"]
channels = ["conda-forge"]
name = "i40"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
seaborn = ">=0.13.2,<0.14"
jupyterlab = ">=4.4.3,<5"
scikit-learn = ">=1.7.0,<2"
