[workspace]
authors = ["ThePieroCV <piero.casusolv@pucp.edu.pe>"]
channels = ["conda-forge"]
name = "i40"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
torch = { version = ">=2.7.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.22.1", index = "https://download.pytorch.org/whl/cu128" }
roboflow = ">=1.1.66, <2"
opencv-python = ">=4.11.0.86, <5"
ultralytics = ">=8.3.158, <9"
jupyterlab = ">=4.4.3, <5"
langchain = ">=0.3.26, <0.4"
langgraph = ">=0.4.8, <0.5"
google-generativeai = ">=0.8.5, <0.9"
pillow = ">=11.2.1, <12"
jupyter = ">=1.1.1, <2"
ipython = ">=9.3.0, <10"
matplotlib = ">=3.10.3, <4"
python-dotenv = ">=1.1.0, <2"
